### ISSUE TITLE
连接mysql8.X报错

### ISSUE THREAD

**Issue by DoverDee** [chaiyd/zentao#1]
安装到生成配置文件，填写数据库配置时保存了。。。
我的数据库版本：Server version: 8.0.19 MySQL Community Server - GPL
报错信息：数据库连接失败 SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

**Comment by chaiyd** [comment]
安装时数据库地址不要写127.0.0.1或者localhost，写实际ip，如果还是不行，尝试MySQL 5.7吧，8.x这玩意，我也没测试，等有时间吧
