### ISSUE TITLE
.env 文件是不要提交的。

### ISSUE THREAD

**Issue by xiagw** [chaiyd/zentao#5]
已经有一个 env-example
.env 是用户的自定义配置文件，
存储自定义数据的，
一般不提交到库里面。

**Comment by xiagw** [comment]
我给你的 PR 里已经排除掉.env 文件的

**Comment by chaiyd** [comment]
> 已经有一个 env-example
> .env 是用户的自定义配置文件，
> 存储自定义数据的，
> 一般不提交到库里面。

这个目前还需要修改，还在想怎么修改下，比较合理一点，尽量简化用户的操作吧

**Comment by chaiyd** [comment]
> 已经有一个 env-example
> .env 是用户的自定义配置文件，
> 存储自定义数据的，
> 一般不提交到库里面。

这个我考虑下，怎么搞吧，一直没有加env这种文件的原因是觉得太繁琐了。因为不排除完全不懂得用户
