### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by niaiwomattt** [chaiyd/zentao#6]
SQLSTATE[HY000] [2002] No such file or directory

无法连接数据库，报这个错

**Comment by chaiyd** [comment]
这个应该是你本地数据库的原因吧，先看看数据库能不能登录

**Comment by chaiyd** [comment]
docker-compose 我更改过了，你直接使用master 分支的docker-compose 重新启动试试

**Comment by niaiwomattt** [comment]
忘了，我记得好像去 php.ini 里把 PDO_mysql 相关的那个开开就好了

**Comment by chaiyd** [comment]
> 忘了，我记得好像去 php.ini 里把 PDO_mysql 相关的那个开开就好了

我刚才也尝试了，是没有问题的，或者你这边有问题再提吧
